import {PredefinedGamepadModel} from 'gamepad-type';
import {InputDeviceTypeEnum} from 'input-device-handler';
import {BindingDirectionEnum, NamedActionBindingGroups} from './action-binding';
import {ForwardGameAction} from './perform-actions.module';

export const defaultBindingSets = {
    default: {
        isDefault: true,
        name: 'Default',
        bindings: [
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Up,
                direction: BindingDirectionEnum.Positive,
                inputName: 'button-w',
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Down,
                inputName: 'button-s',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Left,
                inputName: 'button-a',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Right,
                inputName: 'button-d',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Pause,
                inputName: 'button-Escape',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Up,
                inputName: 'button-ArrowUp',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Down,
                inputName: 'button-ArrowDown',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Left,
                inputName: 'button-ArrowLeft',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceKey: 'keyboard',
                deviceType: InputDeviceTypeEnum.Keyboard,
                actionName: ForwardGameAction.Right,
                inputName: 'button-ArrowRight',
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },

            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'd-pad-up',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Up,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'd-pad-down',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Down,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'd-pad-left',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Left,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'd-pad-right',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Right,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'options',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Pause,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'left-stick-y',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Up,
                direction: BindingDirectionEnum.Negative,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'left-stick-y',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Down,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'left-stick-x',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Left,
                direction: BindingDirectionEnum.Negative,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'left-stick-x',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Right,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'right-stick-y',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Up,
                direction: BindingDirectionEnum.Negative,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'right-stick-y',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Down,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'right-stick-x',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Left,
                direction: BindingDirectionEnum.Negative,
                inputPlayerIndex: 0,
            },
            {
                deviceType: InputDeviceTypeEnum.Gamepad,
                gamepadLayoutInputName: 'right-stick-x',
                inputName: '',
                gamepadModelName: PredefinedGamepadModel.PlaystationDualSense,
                gamepadName: '',
                actionName: ForwardGameAction.Right,
                direction: BindingDirectionEnum.Positive,
                inputPlayerIndex: 0,
            },
        ],
    },
} as const satisfies NamedActionBindingGroups;
