import {writeFile} from 'fs/promises';
import {formatCode} from './format';

const generatedFileComment = `/** This file is automatically generated, do not manually modify it. **/`;

export async function generateTsFile(code: string, filePath: string): Promise<void> {
    const fullCode = [
        generatedFileComment,
        code,
    ].join('\n\n');
    const formattedCode = await formatCode({text: fullCode, filePath});
    await writeFile(filePath, formattedCode);
}
